### ISSUE TITLE
Donation page Input field validation

### ISSUE THREAD

**Issue by BalajiArumugam-001** [fssa-batch3/isac.abishek__web_project#3]
### Description of issue
Donation page validation

### Expected result
Every input fields should have the data.

### Actual result
Redirecting without fill up the form

### Steps to reproduce
1. add "required" attribute to your input fields

```
Path:      /pages/donarpages/donation.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--freshtrust.netlify.app%2Fpages%2Fdonarpages%2Fdonation.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--freshtrust.netlify.app/pages/donarpages/donation.html)

**Comment by isacdevaabishek** [comment]
fixed the bug balajiarumugam

**Comment by BalajiArumugam-001** [comment]
Closed
